### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MichaelNZ85** [mercuryseries/django-inertia-vue#1]
Hey @mercuryseries,

Thanks for setting up this boilerplate project for Django and Vue!

Could you please add a license? MIT license is good if you're not sure. I have [a fork](https://github.com/MichaelNZ85/django-inertia-vue) of this project so a license would be good, thanks.

Merci pour tout!

**Comment by mercuryseries** [comment]
Hey @MichaelNZ85 
Just added a LICENSE.md file. MIT was used as suggested.
Have a nice day :).
