### ISSUE TITLE
Python dependencies missing

### ISSUE THREAD

**Issue by gtechjsanders** [mercuryseries/django-inertia-vue#2]
Hi @mercuryseries,

Thank you so much for spending the time to put together these example/base repos. 

I appreciate that in reality these repos should be used alongside your video where you show step by step working out the dependencies for both django/python and vite/npm/js however it would also be great from a stand alone perspective to include a requirements.txt file for use with pip as that would ensure you could get all dependencies for both django and vite using the respective standards for creating dependency files.

**Comment by fertek** [comment]
Hi @gtechjsanders,

creating `requirements.txt` next to `package.json` with following content should be enough.

```
Django==4.1.3
inertia-django==0.4.1
django-vite==2.0.2
django-js-routes==0.2.0
```

See https://github.com/fertek/django-inertia-react for more.

**Comment by mercuryseries** [comment]
@gtechjsanders @fertek Sorry for the delay in the response.
A `requirements.txt` file has been added to the repo. Thanks 🎉
