### ISSUE TITLE
How to use reverseUrl in Vue component

### ISSUE THREAD

**Issue by fertek** [mercuryseries/django-inertia-vue#3]
Hi @mercuryseries, thanks for this template.

There is django-js-routes package  [installed](https://github.com/mercuryseries/django-inertia-vue/blob/1cd215562b94b4a75f4568367d02f189ec09816d/templates/base.html#L21), but the links in the Vue component [don't use reverse routing](https://github.com/mercuryseries/django-inertia-vue/blob/1cd215562b94b4a75f4568367d02f189ec09816d/assets/js/components/Layout.vue#L8).

It's easy to make links like `<Link :href="$route('home')">Homepage</Link>` work.

```
const routePlugin = {
    install: (app, _options) => {
        app.config.globalProperties.$route = window.reverseUrl
    }
}

createInertiaApp({
    resolve: async name => {
        const page = (await pages[`./pages/${name}.vue`]()).default;
        page.layout = page.layout || Layout;
        return page;
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(routePlugin)
            .mount(el)
    },
});
```

See [flask-inertia docs](https://flask-inertia.readthedocs.io/en/v0.4/tutorial.html#integrate-inertia) for more.

**Comment by mercuryseries** [comment]
Thanks @fertek 👌. Can you please make a PR for that?
