### ISSUE TITLE
CSRF token not sent to Django

### ISSUE THREAD

**Issue by MichaelNZ85** [mercuryseries/django-inertia-vue#4]
When trying to send an Inertia POST request to Django from Vue, it fails with a 403 error saying that the CSRF token is not included.

![firefox_E1stbrZ15B](https://user-images.githubusercontent.com/15241383/204127358-f3c0be50-f79e-464b-b39e-98437acbd996.png)

I know there is some setup in the main.js file before `createInertiaApp()` for axios, but this doesn't appear to be sent to Django.

![firefox_QaQLmydt1E](https://user-images.githubusercontent.com/15241383/204127397-5dcad301-57c4-4f44-b3a2-43fad9a7a0ae.png)

What do I need to do to send the CSRF token with all POST/PUT/PATCH requests?

**Comment by MichaelNZ85** [comment]
Any time I try to send a POST request, it displays the above message. Comment out `django.middleware.csrf.CsrfViewMiddleware` in settings.py and it works fine

**Comment by mercuryseries** [comment]
@MichaelNZ85 Can you share a GitHub link of your project. This will help to reproduce the problem.

**Comment by MichaelNZ85** [comment]
@mercuryseries [Here](https://github.com/MichaelNZ85/django-inertia-test) is the project I was using initially. I created [a second project](https://github.com/MichaelNZ85/django-inertia-csrf) and got the same error.

In the first project, even commenting out the CSRF middleware doesn't fix the problem - the view is never reached.

**Comment by MichaelNZ85** [comment]
Any update on this?

**Comment by BrandonShar** [comment]
I found this issue via a linked issue on the main repo. 

https://github.com/inertiajs/inertia-django/pull/15

This PR will make sending the token automatic and includes docs on how to setup the front end side to recognize the token name and location. Hopefully that will make this process easier!

**Comment by mercuryseries** [comment]
Thanks @BrandonShar. @MichaelNZ85 Can you please check with the latest version of `inertiajs/inertia-django`and let me know if that solves your issue?

**Comment by MichaelNZ85** [comment]
Yes, that fixed it. Thank you very much!
